var courses = [
    {
      "id": 1,
      "name": "HTML-CSS-BOOTSTRUP",
      "instructor": "John Hales",
      "email": "Sincere@april.biz",
      "price":"99",
      "img": 'https://i.ibb.co/N2wr0v5/11.jpg',
    },
    {
        "id": 2,
        "name": "Core Javascript",
        "instructor": "Justin broaden",
        "email": "Sincere@april.biz",
        "price":"199",
        "img":"https://i.ibb.co/1n97cg3/22.png",
      },
      {
        "id": 3,
        "name": "Advance Javascript",
        "instructor": "Justin broaden",
        "email": "Sincere@april.biz",
        "price":"159",
        "img":"https://i.ibb.co/hyhM2c8/33.png",
      },
      {
        "id": 4,
        "name": "Core React Js",
        "instructor": "Harry Carlin",
        "email": "Sincere@april.biz",
        "price":"199",
        "img":"https://i.ibb.co/6BWj374/44.png",
      },
      {
        "id": 5,
        "name": "Advance React Js",
        "instructor": "Harry Carlin",
        "email": "Sincere@april.biz",
        "price":"299",
        "img":"https://i.ibb.co/ySCTby8/55.png",
      },
      {
        "id": 6,
        "name": "Core React Native",
        "instructor": "Json Carlin",
        "email": "Sincere@april.biz",
        "price":"69",
        "img":"https://i.ibb.co/4KmX8zS/66.jpg",
      },
      {
        "id": 7,
        "name": "Advance React Native",
        "instructor": "Ben Trad",
        "email": "Sincere@april.biz",
        "price":"89",
        "img":"https://i.ibb.co/Dg788fQ/77.jpg",
      },
      {
        "id": 8,
        "name": "Learn Python",
        "instructor": "Ben Harry",
        "email": "Sincere@april.biz",
        "price":"169",
        "img":"https://i.ibb.co/MZPGRT8/88.jpg",
      },
      {
        "id": 9,
        "name": "Django",
        "instructor": "Carlin Harry",
        "email": "Sincere@april.biz",
        "price":"399",
        "img":"https://i.ibb.co/TP7mXJ2/99.png",
      },
      {
        "id": 10,
        "name": "Full Stack Javascript",
        "instructor": "Justin berry",
        "email": "Sincere@april.biz",
        "price":"999",
        "img":"https://i.ibb.co/LvCHSWq/10.png",
      },
      {
        "id": 11,
        "name": "Front End Bootcamp",
        "instructor": "Cherry Meals",
        "email": "Sincere@april.biz",
        "price":"1199",
        "img":"https://i.ibb.co/Sy6wpjt/11.png",
      },
      {
        "id": 12,
        "name": "Learn PHP",
        "instructor": "Json Nike",
        "email": "Sincere@april.biz",
        "price":"19",
        "img":"https://i.ibb.co/jRVShND/12.jpg",
      },
      {
        "id": 13,
        "name": "Learn Laravel",
        "instructor": "Json Nike",
        "email": "Sincere@april.biz",
        "price":"19",
        "img":"https://i.ibb.co/jwDScLh/13.png",
      },
      {
        "id": 14,
        "name": "Node Js",
        "instructor": "Justin backon",
        "email": "Sincere@april.biz",
        "price":"299",
        "img":"https://i.ibb.co/tBYLZw9/14.png",
      },
      {
        "id": 15,
        "name": "SQL with Mysql",
        "instructor": "Hello Jah",
        "email": "Sincere@april.biz",
        "price":"199",
        "img":"https://i.ibb.co/87x8hYt/15.jpg",
      }
 ]
 export default courses;